"""correccion en tipo aula

Revision ID: 4aad471f944f
Revises: 197397f41101
Create Date: 2025-08-08 17:09:27.673620

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4aad471f944f'
down_revision: Union[str, None] = '197397f41101'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asignaturas', sa.Column('tipo_aula', sa.String(), nullable=True))
    op.drop_constraint('asignaturas_aula_id_fkey', 'asignaturas', type_='foreignkey')
    op.drop_column('asignaturas', 'aula_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asignaturas', sa.Column('aula_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('asignaturas_aula_id_fkey', 'asignaturas', 'aulas', ['aula_id'], ['id'])
    op.drop_column('asignaturas', 'tipo_aula')
    # ### end Alembic commands ###
