"""migraciones

Revision ID: 76340986df61
Revises: 
Create Date: 2025-05-14 16:18:47.347228

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76340986df61'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asignaturas', sa.Column('docente_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'asignaturas', 'programas', ['programa_id'], ['id'])
    op.create_foreign_key(None, 'asignaturas', 'docentes', ['docente_id'], ['id'])
    op.create_foreign_key(None, 'sede_programa', 'programas', ['programa_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sede_programa', type_='foreignkey')
    op.drop_constraint(None, 'asignaturas', type_='foreignkey')
    op.drop_constraint(None, 'asignaturas', type_='foreignkey')
    op.drop_column('asignaturas', 'docente_id')
    # ### end Alembic commands ###
