"""se añade campo sede

Revision ID: 7ff546eb60c2
Revises: b077f98edb34
Create Date: 2025-08-08 02:07:07.941675

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ff546eb60c2'
down_revision: Union[str, None] = 'b077f98edb34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asignaturas', sa.Column('aula_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'asignaturas', 'aulas', ['aula_id'], ['id'])
    op.drop_column('asignaturas', 'aula')
    op.add_column('aulas', sa.Column('sede_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'aulas', 'sedes', ['sede_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'aulas', type_='foreignkey')
    op.drop_column('aulas', 'sede_id')
    op.add_column('asignaturas', sa.Column('aula', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'asignaturas', type_='foreignkey')
    op.drop_column('asignaturas', 'aula_id')
    # ### end Alembic commands ###
