"""docente_id eliminado del modelo

Revision ID: fce0de49540c
Revises: 76340986df61
Create Date: 2025-05-15 10:56:52.597778

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fce0de49540c'
down_revision: Union[str, None] = '76340986df61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('asignaturas_docente_id_fkey', 'asignaturas', type_='foreignkey')
    op.drop_column('asignaturas', 'docente_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asignaturas', sa.Column('docente_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('asignaturas_docente_id_fkey', 'asignaturas', 'docentes', ['docente_id'], ['id'])
    # ### end Alembic commands ###
